### ISSUE TITLE
How to center align nodes in horizontal placement

### ISSUE THREAD

**Issue by idea-launch-lab** [OpenKieler/klayjs-d3#12]
Hi, I would like to know how to align all nodes in left-to-right layout such that nodes are at the same level horizontally. Below is current layout where nodes are incrementally offset in vertical direction; I'd like the nodes to be placed on a same horizontal level.
I experimented with port alignment but I'd like to keep ports center-aligned east/west side of the nodes. 
Thanks.

<img width="654" alt="screen shot 2016-11-01 at 11 07 49 pm" src="https://cloud.githubusercontent.com/assets/5922613/19915453/c1d300cc-a088-11e6-8080-8c9dd335531f.png">

**Comment by uruuru** [comment]
In other words, the edges should have bends? You could try setting `nodePlace: "SIMPLE"` on the surrounding node (the gray one). However, you may dislike that solution if there are two or more nodes stacked vertically (i.e., in the same layer).

**Comment by idea-launch-lab** [comment]
Okay, thanks. I tried your solution and below is what I get. It solved my original problem of aligning nodes on same horizontal level. Is there a way to not have additional bend points (ovals)? Thanks.

![screen shot 2016-11-02 at 1 20 01 pm](https://cloud.githubusercontent.com/assets/5922613/19939457/783bd502-a0ff-11e6-9f83-e8983c3b4a0f.png)

**Comment by le-cds** [comment]
The appearance of those bend points is strange. But for this kind of diagram, you may want to switch to the Polyline edge router anyway, which produces no 90 degree bends. If the problem appears with that edge router as well there will be a problem with the ports somewhere, I presume.

**Comment by uruuru** [comment]
@sid-thakur did you give it a try?

**Comment by idea-launch-lab** [comment]
@uruuru The bend points still exist. I did not use a different polyline edge generator, e.g., spline. I ended up going with the original solution that aligns ports in horizontal direction (image in first post in this thread). Thanks.
