### ISSUE TITLE
How to evenly spread out large number of ports

### ISSUE THREAD

**Issue by idea-launch-lab** [OpenKieler/klayjs-d3#9]
Hi, I have nodes that may have a handful of ports (e.g., 10-20 ports) on a single side (input/output). I would like to know how ensure that ports are evenly spread out. See image below for a canonical example of issue I'm having with large number of ports. The ports are either un-evenly positioned (oval on left in the image) or bunched up together (right oval). 

Will the `portSpacing` attribute help with this, if so how should I be using it? I am using the JavaScript library.
Thanks!

![screen shot 2016-10-14 at 2 11 16 pm](https://cloud.githubusercontent.com/assets/5922613/19398349/397cf740-921a-11e6-96e0-3d9e8ee9eb20.png)

**Comment by le-cds** [comment]
What would be the expected result? Even if the ports were spaced evenly (and it's a bit puzzling to me that they aren't, because that's what the algorithm usually tries to do) they wouldn't really be readable because there's not enough space. Would you be okay with the algorithm resizing the nodes appropriately?

**Comment by idea-launch-lab** [comment]
@le-cds Thanks for your response. Yes, while readability of port-labels is an issue with large number of ports, I control scaling of fonts through user's zooming behavior on the SVG canvas. I am also using color to represent port types, which provides some indication about port type when text is small/hidden. 
Regarding behavior of the algorithm, I experimented with changing the node height, and it seems that the default algorithm tries to fit all ports within a fixed vertical space that is equal to node height. Below is image with modified node height (nodes are taller than in previously posted image).

![screen shot 2016-10-17 at 9 38 53 am](https://cloud.githubusercontent.com/assets/5922613/19440027/55129e98-944e-11e6-9e81-8d14b84f8cbd.png)

What I am trying to achieve is to keep node sizes same, but allow ports to be separated evenly. So an option that allows port drawing area to scale freely based on number of port, without having to change node dimension. Something like below:

![screen shot 2016-10-17 at 9 56 44 am](https://cloud.githubusercontent.com/assets/5922613/19440464/0900beca-9450-11e6-93e3-11907cfa0cb4.png)

**Comment by uruuru** [comment]
Sorry for the delay, I was on leave.

You should be able to do this by setting the node's `de.cau.cs.kieler.portAlignment` to `CENTER` and specifying a reasonable value for `de.cau.cs.kieler.portSpacing`, e.g. `5`.

**Comment by idea-launch-lab** [comment]
Thanks. Will try that out..

**Comment by idea-launch-lab** [comment]
@uruuru Port spacing solution worked! Thanks. Here's the code and results:

```
nodeJSON.width = 18;
nodeJSON.height = 10;
nodeJSON ["properties"] = {
     "portConstraints" : "FIXED_SIDE",
     "de.cau.cs.kieler.portAlignment" : "CENTER",
     "de.cau.cs.kieler.portSpacing": 5
};
```

![screen shot 2016-10-27 at 9 49 35 am](https://cloud.githubusercontent.com/assets/5922613/19769867/20032e54-9c2b-11e6-89be-1e3d9e90aca3.png)

**Comment by chandusekhar** [comment]
Is there working sample with hierarchy ,grouping with ports?
